### ISSUE TITLE
Errors after updating to 4.1.4

### ISSUE THREAD

**Issue by catallo** [anasfik/openai#123]
After updating to version 4.1.4, I encountered compilation errors in my code. Here's the specific error message:

Error: The argument type 'String' can't be assigned to the parameter type 'List<OpenAIChatCompletionChoiceMessageContentItemModel>?'.

![image](https://github.com/anasfik/openai/assets/45834058/9873a76b-63f2-47dc-b012-26ebb94c09e5)

**Comment by anasfik** [comment]
Hello, Yes there are breaking changes in it in favor of the new syntax of OpenAI for chat completions to support GPT 4 Vision, check [this](https://platform.openai.com/docs/guides/vision).

The API still process the old requests as normal, as text-content-based messages only, However, so you can upload images to the models as content as well to analyze it, check the [new implementation docs](https://github.com/anasfik/openai#create-chat-completion).


 I guess it was a mistake for me now set the version to 5.0.0 because this is a breaking change.

**Comment by casualcoder404** [comment]
After the latest update, you have to write content as below:

    content: [
          OpenAIChatCompletionChoiceMessageContentItemModel.text(" a string")
        ],

**Comment by catallo** [comment]
Oh OK. Thank you!
